### ISSUE TITLE
Consider keeping header case as given?

### ISSUE THREAD

**Issue by damienalexandre** [tutorcruncher/pydf#23]
I'm using pydf with the wkhtmltopdf "footer-text" option,
but as every parameters are lower cased in:

https://github.com/tutorcruncher/pydf/blob/8f9ce76344d4d32a8e8ac60f289d194cc509fce1/docker-entrypoint.py#L41

My text content is not properly passed througt wkhtmltopdf.

I don't know if there is a reason for this `lower()` call on all argument values? It's ok for the key I guess.

### Reproducer

```
curl -d '<h1>this is html</h1>' -H "pdf-footer-right: UPPERCASE [page]/[topage]" http://localhost:8000/generate.pdf > created.pdf
```

### Result

> uppercase 1/1

### Expected

> UPPERCASE 1/1

**Comment by samuelcolvin** [comment]
Thanks for reporting, it was probably an oversight, please create a PR to fix this.
