### ISSUE TITLE
Can pydf generate from URL directly?

### ISSUE THREAD

**Issue by cychongaspevo** [tutorcruncher/pydf#29]
In the "wkhtmltopdf.py" file it has mention "Generate a pdf from either a url or a html string", how to pass in generate via URL?

**Comment by samuelcolvin** [comment]
Yes, just try it

**Comment by cychongaspevo** [comment]
is it like this ?
pdf = pydf.generate_pdf("", url="https://www.google.com")

**Comment by samuelcolvin** [comment]
`pydf.generate_pdf('https...')`

**Comment by temitopebello** [comment]
Somehow, my pdf content has the url path instead of the content in the url. Is there anything I am missing?  @samuelcolvin `pydf.generate_pdf('https...')`
